spring:
  application:
    name: myProject
  datasource:
    url: jdbc:postgresql://localhost:5432/settlement_perf_db
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

dummy-data:
  enabled: true
  merchant-count: 100
  payment-count: 100000
  target-date-payment-count: 70000
  target-date: 2026-05-08
  batch-size: 1000

benchmark:
  profile: small
  reset-enabled: false
  merchant-count: 100
  payment-count: 100000
  batch-size: 1000
  target-date-sync-enabled: true
